### ISSUE TITLE
memory build up

### ISSUE THREAD

**Issue by stephanschulz** [LingDong-/VisionOSC#3]
Hey Lingdong.

I am noticing that the memory is steadily increasing, to the point that my computer runs out of memory.
I commented out the OSC routines without solving the leak.
When none of the models is selected then the leaking stops.
Would you know how to fix that?
Thanks a bunch.
![Screen Shot 2022-11-14 at 3 05 46 PM](https://user-images.githubusercontent.com/1054816/201755339-213a952c-49fa-47f9-af4a-a5aa35e65623.jpg)

**Comment by LingDong-** [comment]
Hi Stephan,

Sorry about the leak, are you on the latest release? https://github.com/LingDong-/VisionOSC/releases/tag/v0.0.1

In it, I fixed a big memory leak related to Obj-C ARC, and versions of oF (reported by Golan earlier).

If you're using the pre-compiled binary, there should be no leaks now (checked with Instruments.app). But if you're re-compiling from source, you might need to play around with these lines https://github.com/LingDong-/VisionOSC/blob/main/src/body.mm#L20 depending on version of oF...

**Comment by stephanschulz** [comment]
Thanks a bunch. Indeed the newer version works very well. ~130 MB of memory is great.
![Screen Shot 2022-11-15 at 2 31 08 PM](https://user-images.githubusercontent.com/1054816/202008859-4e55f8a8-9fb5-4bda-b4fb-10460d70738e.jpg)
